# Generated by Django 4.2.3 on 2023-07-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
