# Generated by Django 4.2.3 on 2023-07-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeapp', '0004_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=10),
        ),
    ]
