# Generated by Django 4.2.3 on 2023-07-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeapp', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
